LPS-205933 Improving wait mechanism to avoid flakiness
We were getting this error:

Error: expect(locator).toBeVisible()

Locator: frameLocator('iframe[title="Export \\/ Import"]').getByTestId('row').first().locator('.background-task-status-successful')
Expected: visible
Received: hidden
Call log:
  - expect.toBeVisible with timeout 5000ms
  - waiting for frameLocator('iframe[title="Export \\/ Import"]').getByTestId('row').first().locator('.background-task-status-successful')

   at ../pages/export-import-web/exportImportFrame.page.ts:47

  45 | 				.nth(0)
  46 | 				.locator('.background-task-status-successful')
> 47 | 		).toBeVisible();
     | 		  ^
  48 | 	}
  49 |
  50 | 	async close() {